# Generated by Django 4.2.14 on 2026-09-20 23:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('number', models.CharField(help_text='人工填写的唯一商务编号，创建后不得修改', max_length=64, unique=True, verbose_name='单据编号')),
                ('customer_name_snapshot', models.CharField(help_text='本单据正式使用的客户名称，不随客户主数据变化', max_length=255, verbose_name='客户名称快照')),
                ('customer_tax_number_snapshot', models.CharField(blank=True, default='', help_text='本单据正式使用的客户纳税识别信息', max_length=100, verbose_name='客户税号快照')),
                ('customer_address_snapshot', models.TextField(blank=True, default='', help_text='本单据保存时确认的客户地址', verbose_name='客户地址快照')),
                ('contact_name_snapshot', models.CharField(blank=True, default='', help_text='本单据独立保存的联系人姓名，不建立联系人外键', max_length=255, verbose_name='联系人快照')),
                ('contact_phone_snapshot', models.CharField(blank=True, default='', help_text='本单据确认的联系电话', max_length=64, verbose_name='联系电话快照')),
                ('contact_email_snapshot', models.EmailField(blank=True, default='', help_text='本单据确认的商务联系邮箱', max_length=254, verbose_name='联系邮箱快照')),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='人民币含税总额调整，可正可负，但调整后总额不得为负', max_digits=20, verbose_name='调整金额')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='服务端逐行舍入后的人民币含税行金额之和', max_digits=20, verbose_name='小计')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='人民币含税小计加调整金额，服务端保留两位小数', max_digits=20, verbose_name='总额')),
                ('commercial_terms', models.TextField(blank=True, default='', help_text='本单据约定的商务条款，锁定后不得修改', verbose_name='商务条款')),
                ('remark', models.TextField(blank=True, default='', help_text='本单据的补充说明，属于锁定的商务正文', verbose_name='单据备注')),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SIGNED', 'SIGNED'), ('VOID', 'VOID')], default='DRAFT', editable=False, help_text='只能通过签署或作废命令改变', max_length=10, verbose_name='合同状态')),
                ('contract_date', models.DateField(help_text='本合同对外使用的业务日期', verbose_name='合同日期')),
                ('signed_at', models.DateTimeField(editable=False, help_text='签署命令成功时由服务端记录的时间，不代表电子签名', null=True, verbose_name='签署时间')),
                ('voided_at', models.DateTimeField(editable=False, help_text='合同作废命令成功时由服务端记录的时间', null=True, verbose_name='作废时间')),
                ('creator', models.ForeignKey(help_text='创建单据的用户，也是本人数据范围的归属依据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(help_text='保留客户业务关联，正式内容使用独立客户快照', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='customer.customer', verbose_name='客户')),
                ('signed_by', models.ForeignKey(editable=False, help_text='执行合同签署命令的用户，不代表法律电子签名', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='签署操作人')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='同一单据内唯一的方案分组显示顺序', verbose_name='分组顺序')),
                ('name_snapshot', models.CharField(help_text='单据正式展示的方案或自定义商业分组名称', max_length=255, verbose_name='方案名称快照')),
                ('name_en_snapshot', models.CharField(blank=True, default='', help_text='本单据独立保存的英文方案名称', max_length=255, verbose_name='英文方案名称')),
                ('description_snapshot', models.TextField(blank=True, default='', help_text='本单据独立保存的方案适用说明', verbose_name='方案说明快照')),
                ('remark', models.TextField(blank=True, default='', help_text='此商业方案分组的补充说明', verbose_name='分组备注')),
                ('contract', models.ForeignKey(help_text='分组所属合同，只能通过合同聚合接口维护', on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='commercial.contract', verbose_name='合同')),
                ('source_scheme', models.ForeignKey(blank=True, help_text='创建时导入的主方案，仅追溯，删除来源不影响快照', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.scheme', verbose_name='来源方案')),
            ],
            options={
                'verbose_name': '合同方案',
                'verbose_name_plural': '合同方案',
                'ordering': ('sequence', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('number', models.CharField(help_text='人工填写的唯一商务编号，创建后不得修改', max_length=64, unique=True, verbose_name='单据编号')),
                ('customer_name_snapshot', models.CharField(help_text='本单据正式使用的客户名称，不随客户主数据变化', max_length=255, verbose_name='客户名称快照')),
                ('customer_tax_number_snapshot', models.CharField(blank=True, default='', help_text='本单据正式使用的客户纳税识别信息', max_length=100, verbose_name='客户税号快照')),
                ('customer_address_snapshot', models.TextField(blank=True, default='', help_text='本单据保存时确认的客户地址', verbose_name='客户地址快照')),
                ('contact_name_snapshot', models.CharField(blank=True, default='', help_text='本单据独立保存的联系人姓名，不建立联系人外键', max_length=255, verbose_name='联系人快照')),
                ('contact_phone_snapshot', models.CharField(blank=True, default='', help_text='本单据确认的联系电话', max_length=64, verbose_name='联系电话快照')),
                ('contact_email_snapshot', models.EmailField(blank=True, default='', help_text='本单据确认的商务联系邮箱', max_length=254, verbose_name='联系邮箱快照')),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='人民币含税总额调整，可正可负，但调整后总额不得为负', max_digits=20, verbose_name='调整金额')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='服务端逐行舍入后的人民币含税行金额之和', max_digits=20, verbose_name='小计')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='人民币含税小计加调整金额，服务端保留两位小数', max_digits=20, verbose_name='总额')),
                ('commercial_terms', models.TextField(blank=True, default='', help_text='本单据约定的商务条款，锁定后不得修改', verbose_name='商务条款')),
                ('remark', models.TextField(blank=True, default='', help_text='本单据的补充说明，属于锁定的商务正文', verbose_name='单据备注')),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SENT', 'SENT'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('VOID', 'VOID')], default='DRAFT', editable=False, help_text='只能通过发送、接受、拒绝或作废命令改变', max_length=10, verbose_name='报价状态')),
                ('quotation_date', models.DateField(help_text='本报价单对外使用的业务日期', verbose_name='报价日期')),
                ('valid_until', models.DateField(blank=True, help_text='报价有效期的截止日期，可留空', null=True, verbose_name='有效期至')),
                ('sent_at', models.DateTimeField(editable=False, help_text='发送命令成功时由服务端记录的时间', null=True, verbose_name='发送时间')),
                ('accepted_at', models.DateTimeField(editable=False, help_text='接受命令成功时由服务端记录的时间', null=True, verbose_name='接受时间')),
                ('rejected_at', models.DateTimeField(editable=False, help_text='拒绝命令成功时由服务端记录的时间', null=True, verbose_name='拒绝时间')),
                ('voided_at', models.DateTimeField(editable=False, help_text='作废命令成功时由服务端记录的时间', null=True, verbose_name='作废时间')),
                ('accepted_by', models.ForeignKey(editable=False, help_text='执行接受报价命令的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='接受操作人')),
                ('creator', models.ForeignKey(help_text='创建单据的用户，也是本人数据范围的归属依据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(help_text='保留客户业务关联，正式内容使用独立客户快照', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='customer.customer', verbose_name='客户')),
                ('rejected_by', models.ForeignKey(editable=False, help_text='执行拒绝报价命令的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='拒绝操作人')),
                ('sent_by', models.ForeignKey(editable=False, help_text='执行发送报价命令的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
                ('voided_by', models.ForeignKey(editable=False, help_text='执行报价作废命令的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作废人')),
            ],
            options={
                'verbose_name': '报价',
                'verbose_name_plural': '报价',
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='同一单据内唯一的方案分组显示顺序', verbose_name='分组顺序')),
                ('name_snapshot', models.CharField(help_text='单据正式展示的方案或自定义商业分组名称', max_length=255, verbose_name='方案名称快照')),
                ('name_en_snapshot', models.CharField(blank=True, default='', help_text='本单据独立保存的英文方案名称', max_length=255, verbose_name='英文方案名称')),
                ('description_snapshot', models.TextField(blank=True, default='', help_text='本单据独立保存的方案适用说明', verbose_name='方案说明快照')),
                ('remark', models.TextField(blank=True, default='', help_text='此商业方案分组的补充说明', verbose_name='分组备注')),
                ('quotation', models.ForeignKey(help_text='分组所属报价，只能通过报价聚合接口维护', on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='commercial.quotation', verbose_name='报价')),
                ('source_scheme', models.ForeignKey(blank=True, help_text='创建时导入的主方案，仅追溯，删除来源不影响快照', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.scheme', verbose_name='来源方案')),
            ],
            options={
                'verbose_name': '报价方案',
                'verbose_name_plural': '报价方案',
                'ordering': ('sequence', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationSchemeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='同一商业方案分组内唯一的明细显示顺序', verbose_name='明细顺序')),
                ('product_number_snapshot', models.CharField(help_text='创建时的产品稳定编号，普通更新不可修改', max_length=64, verbose_name='产品编号快照')),
                ('name_snapshot', models.CharField(help_text='本行正式商务名称，可在草稿阶段按权限编辑', max_length=255, verbose_name='产品名称快照')),
                ('name_en_snapshot', models.CharField(blank=True, default='', help_text='本行正式英文商务名称', max_length=255, verbose_name='英文产品名称')),
                ('unit_snapshot', models.CharField(help_text='本行商务数量与成交单价使用的计量单位', max_length=64, verbose_name='单位快照')),
                ('requirement_schema', models.JSONField(default=list, editable=False, help_text='创建时服务需求模板的独立副本，普通更新不可修改', verbose_name='需求结构快照')),
                ('requirement_data', models.JSONField(blank=True, default=dict, help_text='依据本行结构快照校验的最终要求，商务阶段允许部分填写', verbose_name='要求实例')),
                ('quantity', models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='大于零的商务计价数量，最多六位小数，不决定任务数量', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='商务数量')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='人民币含税成交单价，允许零价，最多两位小数', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='含税单价')),
                ('line_amount', models.DecimalField(decimal_places=2, editable=False, help_text='数量乘单价后按 HALF_UP 舍入到分的服务端权威金额', max_digits=20, verbose_name='含税行金额')),
                ('remark', models.TextField(blank=True, default='', help_text='该商业明细的技术或商务补充说明', verbose_name='明细备注')),
                ('quotation_scheme', models.ForeignKey(help_text='明细所属报价方案分组，不允许跨父对象移动已有行', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commercial.quotationscheme', verbose_name='报价方案')),
                ('source_product', models.ForeignKey(help_text='新行必须来源于真实产品，来源删除后仍保留独立快照', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='来源产品')),
            ],
            options={
                'verbose_name': '报价方案明细',
                'verbose_name_plural': '报价方案明细',
                'ordering': ('sequence', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractSchemeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='同一商业方案分组内唯一的明细显示顺序', verbose_name='明细顺序')),
                ('product_number_snapshot', models.CharField(help_text='创建时的产品稳定编号，普通更新不可修改', max_length=64, verbose_name='产品编号快照')),
                ('name_snapshot', models.CharField(help_text='本行正式商务名称，可在草稿阶段按权限编辑', max_length=255, verbose_name='产品名称快照')),
                ('name_en_snapshot', models.CharField(blank=True, default='', help_text='本行正式英文商务名称', max_length=255, verbose_name='英文产品名称')),
                ('unit_snapshot', models.CharField(help_text='本行商务数量与成交单价使用的计量单位', max_length=64, verbose_name='单位快照')),
                ('requirement_schema', models.JSONField(default=list, editable=False, help_text='创建时服务需求模板的独立副本，普通更新不可修改', verbose_name='需求结构快照')),
                ('requirement_data', models.JSONField(blank=True, default=dict, help_text='依据本行结构快照校验的最终要求，商务阶段允许部分填写', verbose_name='要求实例')),
                ('quantity', models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='大于零的商务计价数量，最多六位小数，不决定任务数量', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='商务数量')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='人民币含税成交单价，允许零价，最多两位小数', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='含税单价')),
                ('line_amount', models.DecimalField(decimal_places=2, editable=False, help_text='数量乘单价后按 HALF_UP 舍入到分的服务端权威金额', max_digits=20, verbose_name='含税行金额')),
                ('remark', models.TextField(blank=True, default='', help_text='该商业明细的技术或商务补充说明', verbose_name='明细备注')),
                ('contract_scheme', models.ForeignKey(help_text='明细所属合同方案分组，不允许跨父对象移动已有行', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commercial.contractscheme', verbose_name='合同方案')),
                ('source_product', models.ForeignKey(help_text='新行必须来源于真实产品，来源删除后仍保留独立快照', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='来源产品')),
            ],
            options={
                'verbose_name': '合同方案明细',
                'verbose_name_plural': '合同方案明细',
                'ordering': ('sequence', 'id'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='source_quotation',
            field=models.OneToOneField(blank=True, editable=False, help_text='每份报价最多转换为一份合同，仅用于追溯，不动态读取其内容', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_contract', to='commercial.quotation', verbose_name='来源报价'),
        ),
        migrations.AddField(
            model_name='contract',
            name='voided_by',
            field=models.ForeignKey(editable=False, help_text='执行合同作废命令的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作废人'),
        ),
        migrations.AddConstraint(
            model_name='quotationschemeitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='quotationschemeitem_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='quotationschemeitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='quotationschemeitem_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='quotationschemeitem',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('quotation_scheme', 'sequence'), name='quotation_item_sequence'),
        ),
        migrations.AddConstraint(
            model_name='quotationscheme',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('quotation', 'sequence'), name='quotation_scheme_sequence'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', 0)), name='commercial_quotation_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'VOID'])), name='quotation_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='contractschemeitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='contractschemeitem_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='contractschemeitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='contractschemeitem_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='contractschemeitem',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('contract_scheme', 'sequence'), name='contract_item_sequence'),
        ),
        migrations.AddConstraint(
            model_name='contractscheme',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('contract', 'sequence'), name='contract_scheme_sequence'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', 0)), name='commercial_contract_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['DRAFT', 'SIGNED', 'VOID'])), name='contract_status_valid'),
        ),
    ]
