# Generated by Django 4.2.14 on 2026-09-18 12:56

from django.conf import settings
from django.db import migrations, models
from ._b3_preflight import require_clean
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(require_clean, migrations.RunPython.noop),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('sid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_refresh_jti', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'db_table': 'auth_session',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='credential_version',
            field=models.CharField(choices=[('LEGACY_UNKNOWN', 'Legacy unknown'), ('DJANGO_NATIVE', 'Django native')], default='LEGACY_UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='dept',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, help_text='上级部门', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dept', verbose_name='上级部门'),
        ),
        migrations.AlterField(
            model_name='fieldpermission',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_field', to='system.menufield', verbose_name='字段'),
        ),
        migrations.AlterField(
            model_name='fieldpermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='menubutton',
            name='menu',
            field=models.ForeignKey(help_text='关联菜单', on_delete=django.db.models.deletion.CASCADE, related_name='menuPermission', to='system.menu', verbose_name='关联菜单'),
        ),
        migrations.AlterField(
            model_name='menufield',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.menu', verbose_name='菜单'),
        ),
        migrations.AlterField(
            model_name='messagecentertargetuser',
            name='messagecenter',
            field=models.ForeignKey(help_text='关联消息中心表', on_delete=django.db.models.deletion.CASCADE, to='system.messagecenter', verbose_name='关联消息中心表'),
        ),
        migrations.AlterField(
            model_name='messagecentertargetuser',
            name='users',
            field=models.ForeignKey(help_text='关联用户表', on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL, verbose_name='关联用户表'),
        ),
        migrations.AlterField(
            model_name='rolemenubuttonpermission',
            name='dept',
            field=models.ManyToManyField(blank=True, help_text='数据权限-关联部门', to='system.dept', verbose_name='数据权限-关联部门'),
        ),
        migrations.AlterField(
            model_name='rolemenubuttonpermission',
            name='menu_button',
            field=models.ForeignKey(help_text='关联菜单按钮', on_delete=django.db.models.deletion.CASCADE, related_name='menu_button_permission', to='system.menubutton', verbose_name='关联菜单按钮'),
        ),
        migrations.AlterField(
            model_name='rolemenubuttonpermission',
            name='role',
            field=models.ForeignKey(help_text='关联角色', on_delete=django.db.models.deletion.CASCADE, related_name='role_menu_button', to='system.role', verbose_name='关联角色'),
        ),
        migrations.AlterField(
            model_name='rolemenupermission',
            name='menu',
            field=models.ForeignKey(help_text='关联菜单', on_delete=django.db.models.deletion.CASCADE, related_name='role_menu', to='system.menu', verbose_name='关联菜单'),
        ),
        migrations.AlterField(
            model_name='rolemenupermission',
            name='role',
            field=models.ForeignKey(help_text='关联角色', on_delete=django.db.models.deletion.CASCADE, related_name='role_menu', to='system.role', verbose_name='关联角色'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父级', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.systemconfig', verbose_name='父级'),
        ),
        migrations.AlterField(
            model_name='users',
            name='dept',
            field=models.ForeignKey(blank=True, help_text='关联部门', null=True, on_delete=django.db.models.deletion.PROTECT, to='system.dept', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.ManyToManyField(blank=True, help_text='关联角色', to='system.role', verbose_name='关联角色'),
        ),
        migrations.AddConstraint(
            model_name='dept',
            constraint=models.CheckConstraint(check=models.Q(('parent', models.F('id')), _negated=True), name='b3_dept_no_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='fieldpermission',
            constraint=models.UniqueConstraint(fields=('role', 'field'), name='b3_role_field_unique'),
        ),
        migrations.AddConstraint(
            model_name='menufield',
            constraint=models.UniqueConstraint(fields=('menu', 'model', 'field_name'), name='b3_menu_field_unique'),
        ),
        migrations.AddConstraint(
            model_name='messagecentertargetuser',
            constraint=models.UniqueConstraint(fields=('messagecenter', 'users'), name='b3_message_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='rolemenubuttonpermission',
            constraint=models.UniqueConstraint(fields=('role', 'menu_button'), name='b3_role_button_unique'),
        ),
        migrations.AddConstraint(
            model_name='rolemenubuttonpermission',
            constraint=models.CheckConstraint(check=models.Q(('data_range__in', [0, 1, 2, 3, 4])), name='b3_grant_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='rolemenupermission',
            constraint=models.UniqueConstraint(fields=('role', 'menu'), name='b3_role_menu_unique'),
        ),
        migrations.AddConstraint(
            model_name='systemconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('key',), name='b3_root_config_key_unique'),
        ),
        migrations.AddField(
            model_name='authsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
