# Generated by Django 4.2.14 on 2026-09-19 00:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_operationlog_request_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('storage_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('size', models.BigIntegerField(editable=False)),
                ('sha256', models.CharField(db_index=True, editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected SHA-256 hex digest.')])),
                ('content_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_managed_file',
                'ordering': ('-id',),
            },
        ),
        migrations.AddConstraint(
            model_name='managedfile',
            constraint=models.CheckConstraint(check=models.Q(('size__gt', 0)), name='managed_file_size_positive'),
        ),
    ]
