# Generated by Django 4.2.14 on 2026-09-20 22:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('costing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('number', models.CharField(help_text='主数据的唯一稳定编号，创建后不可修改，由人工维护', max_length=64, unique=True, verbose_name='主数据编号')),
                ('name', models.CharField(help_text='用于业务识别与正式文件展示的中文名称', max_length=255, verbose_name='正式名称')),
                ('enabled', models.BooleanField(default=True, help_text='停用后禁止新建下游引用，已有关系仍可读取和计算', verbose_name='启用状态')),
                ('description', models.TextField(blank=True, default='', help_text='记录主数据的用途、适用范围和必要业务说明', verbose_name='业务说明')),
                ('internal_name', models.CharField(blank=True, default='', help_text='仅用于实验室内部检索和识别，不直接用于正式对外文件', max_length=255, verbose_name='内部名称')),
                ('name_en', models.CharField(blank=True, default='', help_text='用于英文正式商务文件的业务名称', max_length=255, verbose_name='英文正式名称')),
                ('requirement_defaults', models.JSONField(blank=True, default=dict, help_text='按技术服务需求模板设置产品层默认参数，与方案覆盖值采用浅合并', verbose_name='需求默认值')),
                ('unit', models.CharField(help_text='定义单位成本或产品报价对应的标准计量单位', max_length=64, verbose_name='计价单位')),
                ('reference_price', models.DecimalField(decimal_places=2, help_text='产品当前人民币标准参考售价，保留两位小数，不代表客户成交价', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='参考售价')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ('number', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('number', models.CharField(help_text='主数据的唯一稳定编号，创建后不可修改，由人工维护', max_length=64, unique=True, verbose_name='主数据编号')),
                ('name', models.CharField(help_text='用于业务识别与正式文件展示的中文名称', max_length=255, verbose_name='正式名称')),
                ('enabled', models.BooleanField(default=True, help_text='停用后禁止新建下游引用，已有关系仍可读取和计算', verbose_name='启用状态')),
                ('description', models.TextField(blank=True, default='', help_text='记录主数据的用途、适用范围和必要业务说明', verbose_name='业务说明')),
                ('internal_name', models.CharField(blank=True, default='', help_text='仅用于实验室内部检索和识别，不直接用于正式对外文件', max_length=255, verbose_name='内部名称')),
                ('name_en', models.CharField(blank=True, default='', help_text='用于英文正式商务文件的业务名称', max_length=255, verbose_name='英文正式名称')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '技术方案',
                'verbose_name_plural': '技术方案',
                'ordering': ('number', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('number', models.CharField(help_text='主数据的唯一稳定编号，创建后不可修改，由人工维护', max_length=64, unique=True, verbose_name='主数据编号')),
                ('name', models.CharField(help_text='用于业务识别与正式文件展示的中文名称', max_length=255, verbose_name='正式名称')),
                ('enabled', models.BooleanField(default=True, help_text='停用后禁止新建下游引用，已有关系仍可读取和计算', verbose_name='启用状态')),
                ('description', models.TextField(blank=True, default='', help_text='记录主数据的用途、适用范围和必要业务说明', verbose_name='业务说明')),
                ('internal_name', models.CharField(blank=True, default='', help_text='仅用于实验室内部检索和识别，不直接用于正式对外文件', max_length=255, verbose_name='内部名称')),
                ('name_en', models.CharField(blank=True, default='', help_text='用于英文正式商务文件的业务名称', max_length=255, verbose_name='英文正式名称')),
                ('service_type', models.CharField(blank=True, default='', help_text='用于服务检索与分组，不决定动态模板内容', max_length=64, verbose_name='服务分类')),
                ('requirement_template', models.JSONField(blank=True, default=list, help_text='定义后续任务需求字段，修改不得使现有产品默认值或方案覆盖值失效', verbose_name='需求模板')),
                ('result_template', models.JSONField(blank=True, default=list, help_text='定义后续任务结果字段和表格列，当前仅维护模板定义', verbose_name='结果模板')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '技术服务',
                'verbose_name_plural': '技术服务',
                'ordering': ('number', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchemeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='方案内唯一的明细显示顺序，不表示强制前置依赖或任务数量', verbose_name='显示顺序')),
                ('requirement_override', models.JSONField(blank=True, default=dict, help_text='覆盖产品默认参数的方案行配置，必须符合关联服务当前需求模板', verbose_name='需求覆盖值')),
                ('remark', models.TextField(blank=True, default='', help_text='记录本配置行的技术要求补充说明，不表示报价或合同条款', verbose_name='明细备注')),
                ('product', models.ForeignKey(help_text='引用服务的稳定成本与商务变体，被引用时受关系授权约束', on_delete=django.db.models.deletion.PROTECT, related_name='scheme_items', to='catalog.product', verbose_name='产品')),
                ('scheme', models.ForeignKey(help_text='明细所属的标准技术方案，明细随所属方案删除', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.scheme', verbose_name='技术方案')),
            ],
            options={
                'verbose_name': '方案明细',
                'verbose_name_plural': '方案明细',
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductCostPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, help_text='成本组合的正数用量或换算系数，最多六位小数，不决定任务数量', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='标准用量')),
                ('sequence', models.PositiveIntegerField(default=10, help_text='用于明细展示与排序，不表示强制前置依赖或任务数量', verbose_name='显示顺序')),
                ('package', models.ForeignKey(help_text='被组合或引用的标准成本包，具体删除策略由所属明细关系决定', on_delete=django.db.models.deletion.PROTECT, related_name='product_packages', to='costing.costpackage', verbose_name='成本包')),
                ('product', models.ForeignKey(help_text='引用服务的稳定成本与商务变体，被引用时受关系授权约束', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='catalog.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品成本包',
                'verbose_name_plural': '产品成本包',
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='service',
            field=models.ForeignKey(help_text='产品使用的技术服务定义及需求模板来源', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.service', verbose_name='技术服务'),
        ),
        migrations.AddConstraint(
            model_name='schemeitem',
            constraint=models.UniqueConstraint(fields=('scheme', 'sequence'), name='lims_scheme_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='productcostpackage',
            constraint=models.UniqueConstraint(fields=('product', 'package'), name='lims_product_package_unique'),
        ),
        migrations.AddConstraint(
            model_name='productcostpackage',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='lims_product_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('reference_price__gte', 0)), name='lims_price_nonnegative'),
        ),
    ]
