# Generated by Django 4.2.14 on 2026-09-20 18:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('number', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('LABOR', 'LABOR'), ('EQUIPMENT', 'EQUIPMENT'), ('CONSUMABLE', 'CONSUMABLE'), ('CERTIFICATION', 'CERTIFICATION'), ('MAINTENANCE', 'MAINTENANCE'), ('REPAIR', 'REPAIR'), ('OPERATION', 'OPERATION')], max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(max_length=64)),
                ('basis_data', models.JSONField(blank=True, default=dict)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('number', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CostPackage',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('number', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(max_length=64)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('number', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('number', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('internal_name', models.CharField(blank=True, default='', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('requirement_defaults', models.JSONField(blank=True, default=dict)),
                ('unit', models.CharField(max_length=64)),
                ('reference_price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('number', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('number', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('internal_name', models.CharField(blank=True, default='', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('number', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('number', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('internal_name', models.CharField(blank=True, default='', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('service_type', models.CharField(blank=True, default='', max_length=64)),
                ('requirement_template', models.JSONField(blank=True, default=list)),
                ('result_template', models.JSONField(blank=True, default=list)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('number', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchemeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('requirement_override', models.JSONField(blank=True, default=dict)),
                ('remark', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheme_items', to='lims.product')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lims.scheme')),
            ],
            options={
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductCostPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_packages', to='lims.costpackage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='lims.product')),
            ],
            options={
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='lims.service'),
        ),
        migrations.CreateModel(
            name='CostPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_items', to='lims.costitem')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lims.costpackage')),
            ],
            options={
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='schemeitem',
            constraint=models.UniqueConstraint(fields=('scheme', 'sequence'), name='lims_scheme_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='productcostpackage',
            constraint=models.UniqueConstraint(fields=('product', 'package'), name='lims_product_package_unique'),
        ),
        migrations.AddConstraint(
            model_name='productcostpackage',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='lims_product_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('reference_price__gte', 0)), name='lims_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='costpackageitem',
            constraint=models.UniqueConstraint(fields=('package', 'item'), name='lims_package_item_unique'),
        ),
        migrations.AddConstraint(
            model_name='costpackageitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='lims_package_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_cost__gte', 0)), name='lims_item_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['LABOR', 'EQUIPMENT', 'CONSUMABLE', 'CERTIFICATION', 'MAINTENANCE', 'REPAIR', 'OPERATION'])), name='lims_item_type_valid'),
        ),
    ]
