# Generated by Django 4.2.14 on 2026-09-20 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('number', models.CharField(help_text='主数据的唯一稳定编号，创建后不可修改，由人工维护', max_length=64, unique=True, verbose_name='主数据编号')),
                ('name', models.CharField(help_text='用于业务识别与正式文件展示的中文名称', max_length=255, verbose_name='正式名称')),
                ('enabled', models.BooleanField(default=True, help_text='停用后禁止新建下游引用，已有关系仍可读取和计算', verbose_name='启用状态')),
                ('description', models.TextField(blank=True, default='', help_text='记录主数据的用途、适用范围和必要业务说明', verbose_name='业务说明')),
                ('short_name', models.CharField(blank=True, default='', help_text='供实验室内部搜索和识别客户使用', max_length=255, verbose_name='客户简称')),
                ('tax_number', models.CharField(blank=True, default='', help_text='客户用于商务文件的纳税识别信息', max_length=100, verbose_name='税号')),
                ('address', models.TextField(blank=True, default='', help_text='初始化商务单据客户地址快照的来源', verbose_name='客户地址')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ('number', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='供选择联系人和初始化商务联系信息使用', max_length=255, verbose_name='联系人姓名')),
                ('department', models.CharField(blank=True, default='', help_text='联系人在客户组织中所属的部门', max_length=255, verbose_name='联系人部门')),
                ('title', models.CharField(blank=True, default='', help_text='联系人在客户组织中承担的职务', max_length=255, verbose_name='职务')),
                ('phone', models.CharField(blank=True, default='', help_text='商务沟通使用的固定联系电话', max_length=64, verbose_name='电话')),
                ('mobile', models.CharField(blank=True, default='', help_text='商务沟通使用的移动电话号码', max_length=64, verbose_name='手机')),
                ('email', models.EmailField(blank=True, default='', help_text='商务联系使用的电子邮件地址', max_length=254, verbose_name='电子邮箱')),
                ('address', models.TextField(blank=True, default='', help_text='联系人使用的通讯或收件地址', verbose_name='联系地址')),
                ('is_default', models.BooleanField(default=False, help_text='每个客户最多有一个启用的默认联系人', verbose_name='默认联系人')),
                ('enabled', models.BooleanField(default=True, help_text='停用联系人不占用启用默认联系人的唯一名额', verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', help_text='补充与此联系人有关的商务沟通说明', verbose_name='备注')),
                ('customer', models.ForeignKey(help_text='联系人所属客户，随未被引用的客户一起删除', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customer.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '客户联系人',
                'verbose_name_plural': '客户联系人',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='customercontact',
            constraint=models.UniqueConstraint(condition=models.Q(('enabled', True), ('is_default', True)), fields=('customer',), name='customer_enabled_default_unique'),
        ),
    ]
