# Generated by Django 4.2.14 on 2026-09-20 22:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('number', models.CharField(help_text='主数据的唯一稳定编号，创建后不可修改，由人工维护', max_length=64, unique=True, verbose_name='主数据编号')),
                ('name', models.CharField(help_text='用于业务识别与正式文件展示的中文名称', max_length=255, verbose_name='正式名称')),
                ('enabled', models.BooleanField(default=True, help_text='停用后禁止新建下游引用，已有关系仍可读取和计算', verbose_name='启用状态')),
                ('description', models.TextField(blank=True, default='', help_text='记录主数据的用途、适用范围和必要业务说明', verbose_name='业务说明')),
                ('type', models.CharField(choices=[('LABOR', 'LABOR'), ('EQUIPMENT', 'EQUIPMENT'), ('CONSUMABLE', 'CONSUMABLE'), ('CERTIFICATION', 'CERTIFICATION'), ('MAINTENANCE', 'MAINTENANCE'), ('REPAIR', 'REPAIR'), ('OPERATION', 'OPERATION')], help_text='区分人工、设备、耗材、认证、保养、维修和运营标准成本', max_length=20, verbose_name='成本类型')),
                ('unit_cost', models.DecimalField(decimal_places=6, help_text='以人民币计价的最小标准单位成本，最多保留六位小数', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='单位成本')),
                ('unit', models.CharField(help_text='定义单位成本或产品报价对应的标准计量单位', max_length=64, verbose_name='计价单位')),
                ('basis_data', models.JSONField(blank=True, default=dict, help_text='记录成本换算依据、来源参数与说明，不执行公式或表达式', verbose_name='成本依据')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '成本项',
                'verbose_name_plural': '成本项',
                'ordering': ('number', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CostPackage',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('number', models.CharField(help_text='主数据的唯一稳定编号，创建后不可修改，由人工维护', max_length=64, unique=True, verbose_name='主数据编号')),
                ('name', models.CharField(help_text='用于业务识别与正式文件展示的中文名称', max_length=255, verbose_name='正式名称')),
                ('enabled', models.BooleanField(default=True, help_text='停用后禁止新建下游引用，已有关系仍可读取和计算', verbose_name='启用状态')),
                ('description', models.TextField(blank=True, default='', help_text='记录主数据的用途、适用范围和必要业务说明', verbose_name='业务说明')),
                ('unit', models.CharField(help_text='定义单位成本或产品报价对应的标准计量单位', max_length=64, verbose_name='计价单位')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '成本包',
                'verbose_name_plural': '成本包',
                'ordering': ('number', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CostPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, help_text='成本组合的正数用量或换算系数，最多六位小数，不决定任务数量', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='标准用量')),
                ('sequence', models.PositiveIntegerField(default=10, help_text='用于明细展示与排序，不表示强制前置依赖或任务数量', verbose_name='显示顺序')),
                ('item', models.ForeignKey(help_text='成本包引用的最小标准成本项，被引用后禁止删除', on_delete=django.db.models.deletion.PROTECT, related_name='package_items', to='costing.costitem', verbose_name='成本项')),
                ('package', models.ForeignKey(help_text='被组合或引用的标准成本包，具体删除策略由所属明细关系决定', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='costing.costpackage', verbose_name='成本包')),
            ],
            options={
                'verbose_name': '成本包明细',
                'verbose_name_plural': '成本包明细',
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='costpackageitem',
            constraint=models.UniqueConstraint(fields=('package', 'item'), name='lims_package_item_unique'),
        ),
        migrations.AddConstraint(
            model_name='costpackageitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='lims_package_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_cost__gte', 0)), name='lims_item_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['LABOR', 'EQUIPMENT', 'CONSUMABLE', 'CERTIFICATION', 'MAINTENANCE', 'REPAIR', 'OPERATION'])), name='lims_item_type_valid'),
        ),
    ]
