# Generated by Django 4.2.14 on 2026-09-21 13:44

from decimal import Decimal, ROUND_HALF_UP, localcontext
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def map_legacy_costs(apps, schema_editor):
    """Preserve row identities/audit fields; explicitly round before altering SQL scale.

    Deliberately irreversible: the discarded fractional cents cannot be restored.
    """
    alias = schema_editor.connection.alias
    CostType = apps.get_model('costing', 'CostType')
    CostItem = apps.get_model('costing', 'CostItem')
    labels = {'LABOR': '人工', 'EQUIPMENT': '设备', 'CONSUMABLE': '耗材',
              'CERTIFICATION': '认证', 'MAINTENANCE': '维护', 'REPAIR': '维修', 'OPERATION': '运营'}
    types = {number: CostType.objects.using(alias).create(
        number=number, name=name, enabled=True, description='').pk for number, name in labels.items()}
    with localcontext() as context:
        context.prec = 80
        for item in CostItem.objects.using(alias).all().iterator():
            CostItem.objects.using(alias).filter(pk=item.pk).update(
                cost_type_id=types[item.type],
                unit_cost=item.unit_cost.quantize(Decimal('0.01'), rounding=ROUND_HALF_UP))


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('costing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('number', models.CharField(help_text='主数据的唯一稳定编号，创建后不可修改，由人工维护', max_length=64, unique=True, verbose_name='主数据编号')),
                ('name', models.CharField(help_text='用于业务识别与正式文件展示的中文名称', max_length=255, verbose_name='正式名称')),
                ('enabled', models.BooleanField(default=True, help_text='停用后禁止新建下游引用，已有关系仍可读取和计算', verbose_name='启用状态')),
                ('description', models.TextField(blank=True, default='', help_text='记录主数据的用途、适用范围和必要业务说明', verbose_name='业务说明')),
            ],
            options={
                'verbose_name': '成本类型',
                'verbose_name_plural': '成本类型',
                'ordering': ('number', 'id'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='costtype',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costitem',
            name='cost_type',
            field=models.ForeignKey(help_text='成本项所属的成本分类，必须引用已启用的成本类型；停用已有类型不影响历史成本项读取', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_items', to='costing.costtype', verbose_name='成本类型'),
        ),
        migrations.RunPython(map_legacy_costs),
        migrations.AlterField(model_name='costitem', name='cost_type', field=models.ForeignKey(help_text='成本项所属的成本分类，必须引用已启用的成本类型；停用已有类型不影响历史成本项读取', on_delete=django.db.models.deletion.PROTECT, related_name='cost_items', to='costing.costtype', verbose_name='成本类型')),
        migrations.RemoveConstraint(
            model_name='costitem',
            name='lims_item_type_valid',
        ),
        migrations.RemoveField(
            model_name='costitem',
            name='type',
        ),
        migrations.AlterField(
            model_name='costitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='以人民币计价的最小标准单位成本，保留两位小数', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='单位成本'),
        ),
    ]
